import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        안녕
        <ul>
          <li>
            <Link href="/post">Post</Link>
          </li>
          <li>
            <Link href={{
             pathname: '/shop/3/4',
             query: { qq:  "what"}
            }}>Shop</Link>
          </li>
          <li>
            <Link href="/meal/new-movie/xx">HOT</Link>
          </li>
        </ul>
      </main>
    </>
  )
}
